### ISSUE TITLE
autoload.php isn't created correctly

### ISSUE THREAD

**Issue by TheBay0r** [sonatype-nexus-community/nexus-repository-composer#17] opened 2018-04-23 15:17 UTC
I encounter an issue with nexus and composer, where it seems that the `autoload.php` can't be created correctly when the dependencies are hosted on nexus. If only the composer-proxy is used, the   `autoload.php` works fine. When I have dependencies from composer-hosted the autoload.php doesn't seem to include the dependencies correctly. 

I tried to have a look at the [autoload-documentation](https://getcomposer.org/doc/04-schema.md#autoload), but I couldn't really figure out what is the problem here. Especially since autoloading is working fine, when the same dependency is pulled via github/vcs. 

What I saw, also the `composer.lock` looks completely different, depending on if the hosted repository is used or just vcs + composer-proxy.  Also I noticed, when I use vcs I have to install 59 dependencies. Using composer-hosted just installs 52 dependencies

Below I'll show you how the structure in the `composer.lock` is different
Without composer-hosted the structure in the composer.lock looks like this:
```
{
	"name": "{vendor}/{package}",
	"version": "…",
	"source": {
		"type": "git",
		"url": "{url}",
		"reference": "{sha}"
	},
	"dist": {
		"type": "zip",
		"url": "{url}",
		"reference": "{sha}",
		"shasum": ""
	},
	"require": {
		{lot's of dependencies}
	},
	"require-dev": {
		{more dependencies}
	},
	"suggest": {
		{other dependencies}
	},
	"type": "library",
	"autoload": {
		"psr-0": {
			…
		}
	},
	"license": [
		…
	],
	"authors": [{
		…
	}],
	"description": "…",
	"time": "…"
}
```

Below here you'll see how the same package information looks in the `composer.lock` when retrieved from composer-hosted: 
```
{
	"name": "{vendor}/{package}",
	"version": "…",
	"dist": {
		"type": "zip",
		"url": "{url}",
		"reference": null,
		"shasum": null
	},
	"type": "library",
	"time": "…"
}
```

Not having the `source` part seems to be fine, since this missing in all public / proxied repositories the same case.  But missing out on all other sections seems to be critical.

I hope this information is useful. If you need anything else, I'm happy to support you!

**Comment by fjmilens3** [comment] 2018-04-30 04:40
Hello, @TheBay0r! I've actually been out on vacation the past week and haven't been checking up on all this. And your help and support is very appreciated and always welcome by me.

My _suspicion_, like yours, is that we need to have that data in the package info we're sending back in order for the autoload and dependency resolution to work as expected, and that the "minimum" package definition detailed on https://getcomposer.org/doc/05-repositories.md#packages is actually a bit _too_ minimalist in practice.

I would have thought that it would fail over to the contained `composer.json` but that may not be the case (i.e. perhaps the `PackageInterface` in https://github.com/composer/composer/blob/master/src/Composer/Autoload/AutoloadGenerator.php is coming from the JSON we're serving up instead). Again, just throwing out ideas without really looking.

Either way, it looks to me like we'll probably have to significantly expand the amount of information we're extracting from composer.json uploads in hosted, and this also has significant implications for group merge as we'll need to handle that there as well (meaning that we cannot just serve up the minimal subset I've been relying on thus far). I'll take a look at that perhaps after the group work has been merged down so as not to have too many clashes with my other branch?

As a note to the interested, we generally try to be very parsimonious in terms of what metadata we store for a particular format's components or assets and only capture those pieces of information that are obviously useful to the user or necessary for the format's implementation. These get stored in our NoSQL database, but for large attribute maps (in terms of keys or in terms of nested content) we sometimes encounter scalability issues, particularly when multiplied across all the components or assets in all the repositories. So that's the reason why we don't just grab everything and store it in there in the first place.

**Comment by fjmilens3** [comment] 2018-05-03 15:05
@TheBay0r, how bad it would be for you if I made some breaking changes to the current implementation? (You would likely have to recreate your proxy and hosted repositories as the underlying representation of some of the metadata would no longer be backward-compatible.) If not I can just stick the new stuff side-by-side so it should still work, but that's kind of ugly to do for something that's not even really ready for release yet.

Anyone else reading this should chime in as well. I know we _said_ this was basically pre-alpha quality and it's just a personal project, but I also don't want to break things for people who might be depending on this if I can help it.

(But it would be nice to clean some of this stuff up based on what we're finding here, and I don't think our upgrade framework is going to be something we want to pull into this for several reasons.)

**Comment by fjmilens3** [comment] 2018-05-04 06:24
@TheBay0r, no problem on the vacation/moving, I was actually out the past week which is why I took so long responding. My last couple of jobs have actually been as a remote employee so my wife and I travel all over the US with our little dog, so in a sense we're kind of busy "moving" all the time! Enjoy your travels.

When you get some time to test I'm working on a rather major PR at https://github.com/sonatype-nexus-community/nexus-repository-composer/pull/18 for this that should include some of these missing fields. Rather than storing the information as format attributes I'm just regenerating static provider.json files whenever one of the associated assets changes; it might need further improvement at scale but unless there's a really sneaky concurrency issue in there I suspect it'll work for most people out there once it's finished, assuming that this is actually the root cause of the problem. I still need to tidy it up.

I was also going to ask if you'd like to (or like me to) open a PR to list you as one of our external contributors on the project. You've done an incredible amount of help with testing and sanity-checking my work, and I think your name deserves to be up there too at this point.

**Closed** 2018-05-25 21:21 UTC

**Comment by kuzne4ik537** [comment] 2019-08-13 15:56
Hi which version of Nexus do i need to use to be able to see all  change related to composer.lock
I'm using now Nexus version 3.11 and I have the same issue with composer.lock ( autoload, required ...)
